name: Feature Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  feature-tests:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: your_mysql_root_password
          MYSQL_DATABASE: your_database_name
          MYSQL_USER: your_database_username
          MYSQL_PASSWORD: your_database_password
        ports:
          - 3306:3306
        options: --health-check-interval=10s --health-check-timeout=5s --health-check-retries=3
    
    steps:
      - uses: actions/checkout@v3

      - name: Copy .env file
        run: cp .env.example .env

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run Migrations
        run: php artisan migrate:fresh --seed

      - name: Run Feature Tests
        run: php artisan test --testsuite Feature
